Astro LP price source update to match alphafinance impl
mars-protocol/v1-core pull request #323
Opened 2022-05-04 22:46 UTC by piobab

2022-05-04 23:23 UTC, larry0x commented on contracts/mars-oracle/src/contract.rs
> +        // This formulation avoids a potential sandwich attack that distorts asset prices by a flashloan.
```suggestion
        // This formulation avoids a potential manipulation attack that distorts asset prices by a flashloan.
```

2022-05-04 23:38 UTC, larry0x commented on contracts/mars-oracle/src/contract.rs
> +            assert_eq!(price, Decimal::from_ratio(211_u128, 1000_u128));
can you write some comments on how to arrive at the price? example: https://github.com/mars-protocol/fields-of-mars/blob/v1.0.0/scripts/tests/4_martian_field.test.ts#L418-L421

2022-05-04 23:40 UTC, larry0x commented on contracts/mars-oracle/src/contract.rs
> +            assert_eq!(price, Decimal::from_ratio(211_u128, 1000_u128));
it'd also be helpful to have a unit test to simulate the case where the price is manipulated (e.g. someone dumps a huge amount of Luna in a previous tx of the same block) and see if the calculated price is affected

2022-05-04 23:40 UTC, larry0x commented
@piobab LGTM, with a few comments

2022-05-05 02:29 UTC, dancreee approved these changes

2022-05-05 09:42 UTC, piobab commented on contracts/mars-oracle/src/contract.rs
> +            assert_eq!(price, Decimal::from_ratio(211_u128, 1000_u128));
@larry0x could you please develop your thought? The `AstroportLiquidityToken` price logic takes only pool response from Astro (which is mocked and doesn't have relation to other tx, block etc so can't be simulated in the way you wrote) and asset prices from other price sources (which are already covered with tests). Maybe I didn't fully understand you.

2022-05-05 10:33 UTC, larry0x commented on contracts/mars-oracle/src/contract.rs
> +            assert_eq!(price, Decimal::from_ratio(211_u128, 1000_u128));
@piobab don't worry i'll add a commit to this PR. just want to add an extra test case.

2022-05-05 12:24 UTC, alienHunterOnMars approved these changes

2022-05-05 12:35 UTC, larry0x commented on contracts/mars-oracle/src/contract.rs
> +            assert_eq!(price, Decimal::from_ratio(211_u128, 1000_u128));
@piobab done: https://github.com/mars-protocol/mars-core/pull/323/commits/a0a9c5fca80930e980c0668b65d6fe69cebce52a

2022-05-05 12:38 UTC, larry0x commented
@dancreee @alienHunterOnMars i added an extra unit test to the PR. can you approve again

2022-05-05 13:14 UTC, larry0x submitted a review, later dismissed

2022-05-05 13:15 UTC, piobab commented on contracts/mars-oracle/src/contract.rs
> +            // Is slightly (<0.01%) off from the pre-manipulation value. Good enoguh!
```suggestion
            // Is slightly (<0.01%) off from the pre-manipulation value. Good enough!
```

2022-05-05 13:17 UTC, larry0x approved these changes

2022-05-05 13:50 UTC, dancreee approved these changes

2022-05-05 23:34 UTC, larry0x commented
one thing that just came to mind is that when creating the price source, we should assert that the pool is an XYK pool, not a stableswap pool. i'm gonna do a commit for this if it's ok with you @piobab

2022-05-06 00:14 UTC, larry0x commented
> one thing that just came to mind is that when creating the price source, we should assert that the pool is an XYK pool, not a stableswap pool. i'm gonna do a commit for this if it's ok with you @piobab

commit pushed, pls review

2022-05-06 08:32 UTC, piobab commented
> > one thing that just came to mind is that when creating the price source, we should assert that the pool is an XYK pool, not a stableswap pool. i'm gonna do a commit for this if it's ok with you @piobab
> 
> commit pushed, pls review

LGTM

2022-05-06 08:59 UTC, larry0x approved these changes

2022-05-08 12:44 UTC, dancreee requested changes
@piobab LGTM just need to resolve merge conflicts from #320

2022-05-09 07:43 UTC, dancreee approved these changes

2023-06-21 07:45 UTC, closed without merging